<?php
/**
 * Copyright ePay | Dit Online Betalingssystem, (c) 2010.
 * 
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software. 
 * It is also not legal to do any changes to the software and distribute it in your own name / brand. 
 */
//
// Load the epay standard object
//
$standard = Mage::getModel('epay/standard');
?>
<?php echo $standard->getConfigData('title'); ?>
<br />
<?php 
$orderID = Mage::app()->getRequest()->getParam('order_id');
$order = Mage::getModel('sales/order');
$order->load($orderID);
$OrderId = $order->getIncrementId();

$read = Mage::getSingleton('core/resource')->getConnection('core_read');
$row = $read->fetchRow("select * from epay_order_status where orderid = '" . $OrderId . "'");
		
if($row["status"] == '1')
{
	echo $row['tid'] . "<br />";
	echo $standard->calcCardtype($row['cardid']) ." ". $row['cardnopostfix'] . "<br />";
}
else
{
	if(isset($_GET["txnid"]))
	{
		echo $_GET['txnid'] . "<br />";
		echo $standard->calcCardtype($_GET['paymenttype']) ." ". $_GET['cardno'] . "<br />";
	}
}

?>

