<?php
/**
 * Copyright ePay | Dit Online Betalingssystem, (c) 2010.
 * 
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software. 
 * It is also not legal to do any changes to the software and distribute it in your own name / brand. 
 */
//
// Load the epay standard object
//
$standard = Mage::getModel('epay/standard');
$merchantnumber = $standard->getConfigData('merchantnumber', $order ? $order->getStoreId() : null);

?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>											
            <?php echo $this->__('EPAY_LABEL_2') ?>
			<br />
			<iframe style="width:100%; height: 100px;" src="https://relay.ditonlinebetalingssystem.dk/integration/paymentlogos/PaymentLogos.aspx?merchantnumber=<?php echo $merchantnumber ?>&direction=2&padding=2&rows=1&logo=1&showdivs=0&iframe=1" frameborder="0"></iframe>
        </li>
    </ul>
</fieldset>

